---
- name: Installing Google Chrome
  hosts: all
  become: yes
  tasks:
    - name: download Google Chrome repository key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install Google Chrome package
      apt:
        name: google-chrome-stable
        state: present
  
